-- ProjNav VHDL simulation template: tb_image_scalar.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
